"use client";

import Link from "next/link";
import { useRouter } from "next/router";
import { useContext, useEffect, useMemo, useState } from "react";
import { useSession } from "next-auth/react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { FaArrowLeft, FaChevronLeft, FaChevronRight, FaMoon, FaSun } from "react-icons/fa";
import { ThemeContext } from "../../../context/ThemeContext";
import { fetchSlideshow } from "../../../lib/content-client";
import type { SlideshowDeck } from "../../../lib/content-types";

export default function SlideshowPage() {
  const router = useRouter();
  const { slug } = router.query;
  const { status } = useSession();
  const { theme, toggleTheme } = useContext(ThemeContext);
  const [deck, setDeck] = useState<SlideshowDeck | null>(null);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (status === "unauthenticated") {
      router.replace("/login");
    }
  }, [router, status]);

  useEffect(() => {
    if (status !== "authenticated" || typeof slug !== "string") return;

    const controller = new AbortController();

    (async () => {
      try {
        setLoading(true);
        setError("");
        const nextDeck = await fetchSlideshow(slug, controller.signal);
        setDeck(nextDeck);
        setCurrentIndex(0);
      } catch {
        setError("Failed to load slideshow.");
      } finally {
        setLoading(false);
      }
    })();

    return () => controller.abort();
  }, [slug, status]);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (!deck) return;
      if (event.key === "ArrowRight") {
        setCurrentIndex((index) => Math.min(index + 1, deck.slides.length - 1));
      }
      if (event.key === "ArrowLeft") {
        setCurrentIndex((index) => Math.max(index - 1, 0));
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [deck]);

  const activeSlide = useMemo(() => deck?.slides[currentIndex] || null, [currentIndex, deck]);

  return (
    <div
      style={{
        minHeight: "100vh",
        background:
          theme === "dark"
            ? "linear-gradient(180deg, #020617, #0f172a)"
            : "linear-gradient(180deg, #f8fafc, #ffffff)",
      }}
    >
      <main style={{ maxWidth: 1320, margin: "0 auto", padding: "18px 16px 32px" }}>
        <div className="card" style={{ padding: 18, borderRadius: 22 }}>
          <div
            style={{
              display: "flex",
              flexWrap: "wrap",
              alignItems: "center",
              justifyContent: "space-between",
              gap: 12,
            }}
          >
            <div>
              <div style={{ fontSize: 12, fontWeight: 800, color: "var(--muted)" }}>SLIDESHOW PLAYER</div>
              <div style={{ marginTop: 6, fontSize: 28, fontWeight: 900 }}>
                {deck?.title || "Loading slideshow..."}
              </div>
              <div style={{ marginTop: 8, fontSize: 14, color: "var(--muted)" }}>
                Slides are generated by splitting `slideshow-content.md` on `---`
              </div>
            </div>

            <div style={{ display: "flex", flexWrap: "wrap", gap: 10 }}>
              <Link href="/cbt" className="btn btn-outline">
                <FaArrowLeft /> CBT Hub
              </Link>
              <button className="btn btn-outline" onClick={toggleTheme} type="button">
                {theme === "dark" ? <FaSun /> : <FaMoon />}
                {theme === "dark" ? "Light" : "Dark"}
              </button>
            </div>
          </div>
        </div>

        {loading && (
          <div className="card" style={{ padding: 18, borderRadius: 18, marginTop: 18 }}>
            Loading slideshow...
          </div>
        )}

        {!loading && error && (
          <div className="card" style={{ padding: 18, borderRadius: 18, marginTop: 18, color: "crimson" }}>
            {error}
          </div>
        )}

        {!loading && deck && activeSlide && (
          <div style={{ marginTop: 18, display: "grid", gridTemplateColumns: "300px minmax(0, 1fr)", gap: 16 }}>
            <aside className="card" style={{ padding: 16, borderRadius: 22, minWidth: 0 }}>
              <div style={{ fontSize: 13, fontWeight: 800, color: "var(--muted)" }}>SLIDES</div>
              <div style={{ marginTop: 10, display: "grid", gap: 8 }}>
                {deck.slides.map((slide) => (
                  <button
                    key={`${slide.index}-${slide.title}`}
                    type="button"
                    onClick={() => setCurrentIndex(slide.index)}
                    className={slide.index === currentIndex ? "btn btn-primary" : "btn btn-outline"}
                    style={{ justifyContent: "flex-start", width: "100%" }}
                  >
                    {slide.index + 1}. {slide.title}
                  </button>
                ))}
              </div>
            </aside>

            <section className="card" style={{ padding: 22, borderRadius: 22, minWidth: 0 }}>
              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  alignItems: "center",
                  justifyContent: "space-between",
                  gap: 12,
                  marginBottom: 16,
                }}
              >
                <div>
                  <div style={{ fontSize: 13, fontWeight: 800, color: "var(--muted)" }}>
                    Slide {currentIndex + 1} of {deck.slides.length}
                  </div>
                  <div style={{ marginTop: 6, fontSize: 22, fontWeight: 900 }}>{activeSlide.title}</div>
                </div>

                <div style={{ display: "flex", gap: 10 }}>
                  <button
                    className="btn btn-outline"
                    type="button"
                    disabled={currentIndex === 0}
                    onClick={() => setCurrentIndex((index) => Math.max(index - 1, 0))}
                  >
                    <FaChevronLeft /> Prev
                  </button>
                  <button
                    className="btn btn-outline"
                    type="button"
                    disabled={currentIndex >= deck.slides.length - 1}
                    onClick={() =>
                      setCurrentIndex((index) => Math.min(index + 1, deck.slides.length - 1))
                    }
                  >
                    Next <FaChevronRight />
                  </button>
                </div>
              </div>

              <div className="prose" style={{ minHeight: "60vh" }}>
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{activeSlide.markdown}</ReactMarkdown>
              </div>
            </section>
          </div>
        )}
      </main>
    </div>
  );
}
